plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/DescribeClass:
  Exclude:
    - 'spec/browser/**/*'

RSpec/SpecFilePathFormat:
  Enabled: false
